# Generated by Django 6.0 on 2026-01-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_image_alter_orderitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shoppingPrice',
            new_name='shippingPrice',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
